### ISSUE TITLE
injections.hdf contains events that are very close to each other

### ISSUE THREAD

**Issue by nnarenraju** [gwastro/ml-mock-data-challenge-1#8] opened 2021-12-06 12:59 UTC
I took the "tc" values from injections.hdf, sorted them and found the difference between adjacent times. The minimum time duration between two adjacent "tc" is ~0.00019 seconds, and only 145 out of 583,847 injections have a difference of fewer than 6 seconds. All others are 24 seconds or above. Is this intentional?

Code snippet used to check the time difference:
`diff = np.sort(sorted_tc[1:] - sorted_tc[:-1])`

**Comment by MarlinSchaefer** [comment] 2021-12-06 13:14
Thanks for reporting this issue.
It seems to be caused by pycbc_create_injections. I've posted an issue [here](https://github.com/gwastro/pycbc/issues/3893). If the solution is merged, we might want to switch the version of PyCBC. Otherwise we could set in place a workaround.

I'll update this once we know which route we will take.

**Comment by MarlinSchaefer** [comment] 2021-12-09 09:53
This is fixed by the pull request merged into PyCBC [here](https://github.com/gwastro/pycbc/pull/3894). We will require the new version of PyCBC from now on.

**Closed by MarlinSchaefer** 2021-12-09 09:53 UTC
Labels: bug, good first issue
